
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BLANK BLANK_AREA COLLEGE JUDGMENT_AREA KEY_BLANK_FILLING KEY_CHOOSE KEY_INSTRUCTION KEY_JUDGMENT KEY_SHORT_ANSWER LINE_FEED OPTION_SYMBOL PAPER_NAME QUESTION_NUMBER SCHOOL SCHOOL_YEAR SEMESTER TEXTPAPER : PAPER_HEAD PAPER_BODYPAPER_HEAD : SCHOOL COLLEGE SCHOOL_YEAR PAPER_NAME INSTRUCTIONSempty :TEXTs : TEXT TEXTs\n            | TEXTINSTRUCTIONS : KEY_INSTRUCTION INSTRUCTIONINSTRUCTION : QUESTION_NUMBER TEXTs INSTRUCTION\n                    | QUESTION_NUMBER TEXTsPAPER_BODY : SECTION_CHOOSE SECTION_BLANK_FILLING SECTION_JUDGMENT SECTION_SHORT_ANSWERSECTION_CHOOSE : KEY_CHOOSE LIST_CHOOSELIST_CHOOSE : QUESTION_CHOOSE LIST_CHOOSE\n                    | QUESTION_CHOOSEQUESTION_CHOOSE : QUESTION_NUMBER QUESTION_BODY OPTIONSLEFT_BODY : TEXTs\n                | emptyRIGHT_BODY : TEXTs\n                    | emptyOPTIONS : OPTION_SYMBOL TEXTs OPTIONS\n                | OPTION_SYMBOL TEXTsSECTION_BLANK_FILLING : KEY_BLANK_FILLING LIST_BLANK_FILLINGLIST_BLANK_FILLING : QUESTION_BLANK_FILLING LIST_BLANK_FILLING\n                            | QUESTION_BLANK_FILLINGQUESTION_BLANK_FILLING : QUESTION_NUMBER LEFT_BODY BLANK_AREA RIGHT_BODYSECTION_JUDGMENT : KEY_JUDGMENT LIST_JUDGMENTLIST_JUDGMENT :  QUESTION_JUDGMENT LIST_JUDGMENT\n                        | QUESTION_JUDGMENTQUESTION_JUDGMENT : QUESTION_NUMBER QUESTION_BODY JUDGMENT_AREAQUESTION_BODY : TEXTsSECTION_SHORT_ANSWER : KEY_SHORT_ANSWER LIST_SHORT_ANSWERLIST_SHORT_ANSWER : QUESTION_SHORT_ANSWER LIST_SHORT_ANSWER\n                        | QUESTION_SHORT_ANSWERQUESTION_SHORT_ANSWER : QUESTION_NUMBER TEXTs'
    
_lr_action_items = {'SCHOOL':([0,],[3,]),'$end':([1,4,22,24,35,38,39,47,48,],[0,-1,-5,-9,-4,-29,-31,-30,-32,]),'KEY_CHOOSE':([2,22,35,36,45,54,55,],[6,-5,-4,-2,-6,-8,-7,]),'COLLEGE':([3,],[7,]),'KEY_BLANK_FILLING':([5,10,11,19,22,33,35,44,53,],[9,-10,-12,-11,-5,-13,-4,-19,-18,]),'QUESTION_NUMBER':([6,9,11,15,17,22,25,27,33,35,37,39,43,44,48,49,50,51,52,53,54,],[12,18,12,28,18,-5,40,28,-13,-4,46,40,-3,-19,-32,-27,-23,-16,-17,-18,46,]),'SCHOOL_YEAR':([7,],[13,]),'KEY_JUDGMENT':([8,16,17,22,29,35,43,50,51,52,],[15,-20,-22,-5,-21,-4,-3,-23,-16,-17,]),'TEXT':([12,18,22,28,34,40,43,46,],[22,22,22,22,22,22,22,22,]),'PAPER_NAME':([13,],[23,]),'KEY_SHORT_ANSWER':([14,26,27,41,49,],[25,-24,-26,-25,-27,]),'BLANK_AREA':([18,22,30,31,32,35,],[-3,-5,43,-14,-15,-4,]),'OPTION_SYMBOL':([20,21,22,35,44,],[34,-28,-5,-4,34,]),'JUDGMENT_AREA':([21,22,35,42,],[-28,-5,-4,49,]),'KEY_INSTRUCTION':([23,],[37,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'PAPER':([0,],[1,]),'PAPER_HEAD':([0,],[2,]),'PAPER_BODY':([2,],[4,]),'SECTION_CHOOSE':([2,],[5,]),'SECTION_BLANK_FILLING':([5,],[8,]),'LIST_CHOOSE':([6,11,],[10,19,]),'QUESTION_CHOOSE':([6,11,],[11,11,]),'SECTION_JUDGMENT':([8,],[14,]),'LIST_BLANK_FILLING':([9,17,],[16,29,]),'QUESTION_BLANK_FILLING':([9,17,],[17,17,]),'QUESTION_BODY':([12,28,],[20,42,]),'TEXTs':([12,18,22,28,34,40,43,46,],[21,31,35,21,44,48,51,54,]),'SECTION_SHORT_ANSWER':([14,],[24,]),'LIST_JUDGMENT':([15,27,],[26,41,]),'QUESTION_JUDGMENT':([15,27,],[27,27,]),'LEFT_BODY':([18,],[30,]),'empty':([18,43,],[32,52,]),'OPTIONS':([20,44,],[33,53,]),'INSTRUCTIONS':([23,],[36,]),'LIST_SHORT_ANSWER':([25,39,],[38,47,]),'QUESTION_SHORT_ANSWER':([25,39,],[39,39,]),'INSTRUCTION':([37,54,],[45,55,]),'RIGHT_BODY':([43,],[50,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> PAPER","S'",1,None,None,None),
  ('PAPER -> PAPER_HEAD PAPER_BODY','PAPER',2,'p_paper','parser.py',20),
  ('PAPER_HEAD -> SCHOOL COLLEGE SCHOOL_YEAR PAPER_NAME INSTRUCTIONS','PAPER_HEAD',5,'p_paper_head','parser.py',26),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',31),
  ('TEXTs -> TEXT TEXTs','TEXTs',2,'p_texts','parser.py',35),
  ('TEXTs -> TEXT','TEXTs',1,'p_texts','parser.py',36),
  ('INSTRUCTIONS -> KEY_INSTRUCTION INSTRUCTION','INSTRUCTIONS',2,'p_instructions','parser.py',44),
  ('INSTRUCTION -> QUESTION_NUMBER TEXTs INSTRUCTION','INSTRUCTION',3,'p_instruction','parser.py',49),
  ('INSTRUCTION -> QUESTION_NUMBER TEXTs','INSTRUCTION',2,'p_instruction','parser.py',50),
  ('PAPER_BODY -> SECTION_CHOOSE SECTION_BLANK_FILLING SECTION_JUDGMENT SECTION_SHORT_ANSWER','PAPER_BODY',4,'p_paper_body','parser.py',58),
  ('SECTION_CHOOSE -> KEY_CHOOSE LIST_CHOOSE','SECTION_CHOOSE',2,'p_section_choose','parser.py',63),
  ('LIST_CHOOSE -> QUESTION_CHOOSE LIST_CHOOSE','LIST_CHOOSE',2,'p_list_choose','parser.py',70),
  ('LIST_CHOOSE -> QUESTION_CHOOSE','LIST_CHOOSE',1,'p_list_choose','parser.py',71),
  ('QUESTION_CHOOSE -> QUESTION_NUMBER QUESTION_BODY OPTIONS','QUESTION_CHOOSE',3,'p_question_choose','parser.py',81),
  ('LEFT_BODY -> TEXTs','LEFT_BODY',1,'p_left_body','parser.py',86),
  ('LEFT_BODY -> empty','LEFT_BODY',1,'p_left_body','parser.py',87),
  ('RIGHT_BODY -> TEXTs','RIGHT_BODY',1,'p_right_body','parser.py',95),
  ('RIGHT_BODY -> empty','RIGHT_BODY',1,'p_right_body','parser.py',96),
  ('OPTIONS -> OPTION_SYMBOL TEXTs OPTIONS','OPTIONS',3,'p_options','parser.py',104),
  ('OPTIONS -> OPTION_SYMBOL TEXTs','OPTIONS',2,'p_options','parser.py',105),
  ('SECTION_BLANK_FILLING -> KEY_BLANK_FILLING LIST_BLANK_FILLING','SECTION_BLANK_FILLING',2,'p_section_blank_filling','parser.py',115),
  ('LIST_BLANK_FILLING -> QUESTION_BLANK_FILLING LIST_BLANK_FILLING','LIST_BLANK_FILLING',2,'p_list_blank_filling','parser.py',122),
  ('LIST_BLANK_FILLING -> QUESTION_BLANK_FILLING','LIST_BLANK_FILLING',1,'p_list_blank_filling','parser.py',123),
  ('QUESTION_BLANK_FILLING -> QUESTION_NUMBER LEFT_BODY BLANK_AREA RIGHT_BODY','QUESTION_BLANK_FILLING',4,'p_question_blank_filling','parser.py',133),
  ('SECTION_JUDGMENT -> KEY_JUDGMENT LIST_JUDGMENT','SECTION_JUDGMENT',2,'p_section_judgment','parser.py',138),
  ('LIST_JUDGMENT -> QUESTION_JUDGMENT LIST_JUDGMENT','LIST_JUDGMENT',2,'p_list_judgment','parser.py',145),
  ('LIST_JUDGMENT -> QUESTION_JUDGMENT','LIST_JUDGMENT',1,'p_list_judgment','parser.py',146),
  ('QUESTION_JUDGMENT -> QUESTION_NUMBER QUESTION_BODY JUDGMENT_AREA','QUESTION_JUDGMENT',3,'p_question_judgment','parser.py',156),
  ('QUESTION_BODY -> TEXTs','QUESTION_BODY',1,'p_question_body','parser.py',161),
  ('SECTION_SHORT_ANSWER -> KEY_SHORT_ANSWER LIST_SHORT_ANSWER','SECTION_SHORT_ANSWER',2,'p_section_short_answer','parser.py',166),
  ('LIST_SHORT_ANSWER -> QUESTION_SHORT_ANSWER LIST_SHORT_ANSWER','LIST_SHORT_ANSWER',2,'p_list_short_answer','parser.py',173),
  ('LIST_SHORT_ANSWER -> QUESTION_SHORT_ANSWER','LIST_SHORT_ANSWER',1,'p_list_short_answer','parser.py',174),
  ('QUESTION_SHORT_ANSWER -> QUESTION_NUMBER TEXTs','QUESTION_SHORT_ANSWER',2,'p_question_short_answer','parser.py',184),
]
